/**
 * Logos that are drawn without a disc behind them.
 *
 * Generated by `scripts/logo-disc.mjs` from the bundled artwork — run it
 * rather than editing this list, and `scripts/logo-discs.test.ts` fails if the
 * two drift apart.
 *
 * `CoinIcon` puts every logo on a white disc, which for most of them is
 * invisible: their artwork fills the circle. Where it is not invisible, white
 * is often the wrong choice — these marks are pale enough to wash out on it,
 * and read better on whatever surface is behind them. The opposite failure is
 * equally real, which is why the choice is per logo and measured rather than
 * picked: a black-on-transparent mark like Immutable X needs the white disc or
 * it is a hole in the row.
 *
 * 23 of 274 logos.
 */
export const DISCLESS_LOGOS: ReadonlySet<string> = new Set([
  "ADA",
  "CAKE",
  "CRV",
  "ETC",
  "ETH",
  "GAS",
  "HOT",
  "ICP",
  "LTC",
  "NEO",
  "ONT",
  "RVN",
  "SHIB",
  "SOL",
  "SUI",
  "SUSHI",
  "THETA",
  "UNI",
  "USDT",
  "XMR",
  "XTZ",
  "ZEC",
  "ZIL",
]);
